<?php
declare(strict_types=1);

// DymoApiIntroduction SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DymoApiIntroductionUtility::setRegistrar(function (DymoApiIntroductionUtility $u): void {
    $u->clean = [DymoApiIntroductionClean::class, 'call'];
    $u->done = [DymoApiIntroductionDone::class, 'call'];
    $u->make_error = [DymoApiIntroductionMakeError::class, 'call'];
    $u->feature_add = [DymoApiIntroductionFeatureAdd::class, 'call'];
    $u->feature_hook = [DymoApiIntroductionFeatureHook::class, 'call'];
    $u->feature_init = [DymoApiIntroductionFeatureInit::class, 'call'];
    $u->fetcher = [DymoApiIntroductionFetcher::class, 'call'];
    $u->make_fetch_def = [DymoApiIntroductionMakeFetchDef::class, 'call'];
    $u->make_context = [DymoApiIntroductionMakeContext::class, 'call'];
    $u->make_options = [DymoApiIntroductionMakeOptions::class, 'call'];
    $u->make_request = [DymoApiIntroductionMakeRequest::class, 'call'];
    $u->make_response = [DymoApiIntroductionMakeResponse::class, 'call'];
    $u->make_result = [DymoApiIntroductionMakeResult::class, 'call'];
    $u->make_point = [DymoApiIntroductionMakePoint::class, 'call'];
    $u->make_spec = [DymoApiIntroductionMakeSpec::class, 'call'];
    $u->make_url = [DymoApiIntroductionMakeUrl::class, 'call'];
    $u->param = [DymoApiIntroductionParam::class, 'call'];
    $u->prepare_auth = [DymoApiIntroductionPrepareAuth::class, 'call'];
    $u->prepare_body = [DymoApiIntroductionPrepareBody::class, 'call'];
    $u->prepare_headers = [DymoApiIntroductionPrepareHeaders::class, 'call'];
    $u->prepare_method = [DymoApiIntroductionPrepareMethod::class, 'call'];
    $u->prepare_params = [DymoApiIntroductionPrepareParams::class, 'call'];
    $u->prepare_path = [DymoApiIntroductionPreparePath::class, 'call'];
    $u->prepare_query = [DymoApiIntroductionPrepareQuery::class, 'call'];
    $u->graphql_body = [DymoApiIntroductionGraphql::class, 'body'];
    $u->graphql_errors = [DymoApiIntroductionGraphql::class, 'errors'];
    $u->result_basic = [DymoApiIntroductionResultBasic::class, 'call'];
    $u->result_body = [DymoApiIntroductionResultBody::class, 'call'];
    $u->result_headers = [DymoApiIntroductionResultHeaders::class, 'call'];
    $u->transform_request = [DymoApiIntroductionTransformRequest::class, 'call'];
    $u->transform_response = [DymoApiIntroductionTransformResponse::class, 'call'];
});
